'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import theme from '@/theme/theme'
import Header from '@/components/Header'
import { ProvideTheme } from '../context/ProvideTheme'
// const inter = Inter({ subsets: ['latin'] })

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
} */

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className='box-border p-0 m-0 flex max-w-screen max-h-screen min-w-screen min-h-screen justify-center items-center flex-col' >
        <ChakraProvider theme={theme}>
          <ProvideTheme>
            {children}
            </ProvideTheme>
        </ChakraProvider>
      </body>
    </html>
  )
  // <body className={inter.className} >{children}</body>
}
